"use server";
import { prisma } from "@/lib/prisma";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_SERVER_USER,
    pass: process.env.EMAIL_SERVER_PASSWORD,
  },
});

export async function submitAuthenticatedServiceRequest(formData: FormData) {
  const { userId } = await auth();
  if (!userId) {
    throw new Error("You must be logged in to request a service.");
  }
  
  const client = await clerkClient();
  const user = await client.users.getUser(userId);
  const email = user.emailAddresses[0]?.emailAddress || "Unknown Email";
  const name = user.firstName && user.lastName ? `${user.firstName} ${user.lastName}` : user.firstName || "Unknown User";
  
  const serviceType = formData.get("serviceType") as string;
  const message = formData.get("message") as string;
  
  if (!serviceType) {
    return { success: false, error: "Service type is required." };
  }

  const dbUser = await prisma.user.findUnique({ where: { email } });
  
  if (!dbUser) {
    return { success: false, error: "User profile not fully synchronized. Please contact support." };
  }

  await prisma.serviceRequest.create({
    data: {
      applicantId: dbUser.id,
      serviceType,
      message,
    }
  });

  try {
    const alertEmailSetting = await prisma.setting.findUnique({ where: { key: "ADMIN_ALERT_EMAIL" } });
    const alertEmail = alertEmailSetting?.value || "mdshehab204@gmail.com";

    await transporter.sendMail({
      from: '"CodeBlend System" <hello@codeblend.co>', 
      to: alertEmail,
      subject: `🚀 CodeBlend: Authenticated Service Request (${serviceType})`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px;">
          <h2 style="color: #0f172a;">New Service Requested</h2>
          <p style="color: #475569;">An authenticated user from the dashboard has requested a new service.</p>
          <div style="background: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0; margin-top: 16px;">
            <p style="margin: 4px 0;"><strong>Name:</strong> ${name}</p>
            <p style="margin: 4px 0;"><strong>Email:</strong> ${email}</p>
            <p style="margin: 4px 0;"><strong>Service:</strong> ${serviceType}</p>
            <div style="margin-top: 12px; padding-top: 12px; border-top: 1px solid #e2e8f0;">
              <strong>Requirements:</strong>
              <p style="white-space: pre-wrap; margin-top: 4px; color: #334155;">${message || "No additional requirements provided."}</p>
            </div>
          </div>
          <p style="color: #94a3b8; font-size: 13px; margin-top: 24px;">Automatically generated by CodeBlend System</p>
        </div>
      `,
    });
  } catch (err) {
    console.error("Failed to send admin email alert:", err);
  }

  redirect("/dashboard/user/requests");
}
